# Generated by Django 2.1.5 on 2019-02-11 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('research_type', models.CharField(choices=[('Quality improvement only', 'Quality improvement only'), ('Journal publication and quality improvement', 'Journal publication and quality improvement')], max_length=200)),
                ('related_documentation_location', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('internal_investigators_only', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataProjectGrantApplicationReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_applicantion_contact_name', models.CharField(max_length=255)),
                ('grant_id', models.CharField(max_length=100)),
                ('proposed_budget', models.FloatField()),
                ('date_grant_appplication_lodged', models.DateField(blank=True, null=True)),
                ('status_of_review', models.CharField(choices=[('Under review', 'Under review'), ('Reviewed', 'Reviewed')], max_length=100)),
                ('data_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_projects.DataProject')),
            ],
        ),
        migrations.CreateModel(
            name='DataProjectGrantApplicationReviewerScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_quality_score', models.FloatField()),
                ('significance_and_innovation_score', models.FloatField()),
                ('track_record_score', models.FloatField()),
                ('potential_score', models.FloatField()),
                ('comments', models.TextField()),
                ('date_finalised', models.DateField(auto_now_add=True, null=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_projects.DataProjectGrantApplicationReview')),
                ('reviewer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataProjectInvestigator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_projects.DataProject')),
                ('investigator_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataProjectOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('date_created', models.DateField(blank=True, null=True)),
                ('output_type', models.CharField(choices=[('Government report', 'Government report'), ('Conference paper', 'Conference paper'), ('Journal article', 'Journal article')], max_length=200)),
                ('data_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_projects.DataProject')),
            ],
        ),
        migrations.CreateModel(
            name='DataProjectOutputInvestigator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigator_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_output', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_projects.DataProjectOutput')),
            ],
        ),
    ]
