# Generated by Django 2.1.7 on 2019-02-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprojectgrantapplicationreview',
            name='grant_type',
            field=models.CharField(default='Equipment', max_length=255),
            preserve_default=False,
        ),
    ]
