# Generated by Django 2.1.7 on 2019-02-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_projects', '0002_dataprojectgrantapplicationreview_grant_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataprojectoutput',
            old_name='date_created',
            new_name='actual_release_date',
        ),
        migrations.AddField(
            model_name='dataprojectoutput',
            name='expected_release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataprojectoutput',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
