# Generated by Django 2.1.7 on 2019-02-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_projects', '0003_auto_20190221_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprojectgrantapplicationreview',
            name='grant_scheme',
            field=models.CharField(default='Equipment', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataprojectgrantapplicationreview',
            name='grant_year',
            field=models.IntegerField(default=2017),
            preserve_default=False,
        ),
    ]
