# Generated by Django 2.1.7 on 2019-02-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_projects', '0005_dataprojectinvestigator_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataproject',
            name='current_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Not yet active', 'Not yet active'), ('On hold', 'On hold')], default='Active', max_length=100),
            preserve_default=False,
        ),
    ]
