# Generated by Django 2.1.7 on 2019-02-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_projects', '0008_dataprojectoutput_output_title_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprojectoutput',
            name='publication_or_conference_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dataprojectoutput',
            name='publication_or_conference_name_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
