# Generated by Django 2.1.7 on 2019-02-21 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_projects', '0009_auto_20190221_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataprojectoutput',
            name='output_title_link',
        ),
        migrations.RemoveField(
            model_name='dataprojectoutput',
            name='publication_or_conference_name_link',
        ),
    ]
