# Generated by Django 2.1.7 on 2019-03-14 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_projects', '0013_dataproject_ethics_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataprojectgrantapplicationreviewerscore',
            name='potential_score',
        ),
    ]
