# Generated by Django 2.1.7 on 2019-03-21 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_projects', '0014_remove_dataprojectgrantapplicationreviewerscore_potential_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataprojectgrantapplicationreview',
            name='data_project',
        ),
    ]
