# Generated by Django 2.1.7 on 2019-03-21 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_projects', '0015_remove_dataprojectgrantapplicationreview_data_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataprojectgrantapplicationreview',
            old_name='grant_applicantion_contact_name',
            new_name='administering_organisation',
        ),
        migrations.RenameField(
            model_name='dataprojectgrantapplicationreview',
            old_name='grant_scheme',
            new_name='ci_name',
        ),
        migrations.RenameField(
            model_name='dataprojectgrantapplicationreview',
            old_name='grant_type',
            new_name='ci_prefix',
        ),
        migrations.RemoveField(
            model_name='dataprojectgrantapplicationreview',
            name='grant_year',
        ),
    ]
