# Generated by Django 2.1.7 on 2019-03-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_projects', '0016_auto_20190321_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataprojectgrantapplicationreviewerscore',
            old_name='scientific_quality_score',
            new_name='significance_score',
        ),
        migrations.RenameField(
            model_name='dataprojectgrantapplicationreviewerscore',
            old_name='significance_and_innovation_score',
            new_name='sustainability_score',
        ),
        migrations.RenameField(
            model_name='dataprojectgrantapplicationreviewerscore',
            old_name='track_record_score',
            new_name='team_track_record_score',
        ),
        migrations.AddField(
            model_name='dataprojectgrantapplicationreviewerscore',
            name='translation_score',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
    ]
