# Generated by Django 2.1.7 on 2019-03-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_projects', '0017_auto_20190321_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataprojectgrantapplicationreview',
            old_name='grant_id',
            new_name='grant_application_id',
        ),
        migrations.AddField(
            model_name='dataprojectgrantapplicationreview',
            name='application_title',
            field=models.CharField(default='tyest', max_length=255),
            preserve_default=False,
        ),
    ]
