# Generated by Django 2.1.7 on 2019-03-21 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_projects', '0018_auto_20190321_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataprojectgrantapplicationreview',
            old_name='administering_organisation',
            new_name='lead_organisation',
        ),
        migrations.RemoveField(
            model_name='dataprojectgrantapplicationreview',
            name='date_grant_appplication_lodged',
        ),
        migrations.RemoveField(
            model_name='dataprojectgrantapplicationreview',
            name='proposed_budget',
        ),
    ]
