# Generated by Django 2.1.7 on 2019-03-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_projects', '0019_auto_20190321_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprojectgrantapplicationreview',
            name='administering_organisation',
            field=models.CharField(default='tasdfa', max_length=255),
            preserve_default=False,
        ),
    ]
