# Generated by Django 2.1.7 on 2019-03-21 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_projects', '0020_dataprojectgrantapplicationreview_administering_organisation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataprojectgrantapplicationreview',
            old_name='grant_application_id',
            new_name='grant_id',
        ),
    ]
