# Generated by Django 2.2 on 2019-05-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_projects', '0022_auto_20190510_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprojectoutput',
            name='has_atsi_content',
            field=models.BooleanField(default=False),
        ),
    ]
