# Generated by Django 2.2 on 2019-05-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_projects', '0023_dataprojectoutput_has_atsi_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprojectoutput',
            name='related_documentation',
            field=models.CharField(default='EFF/88', max_length=100),
            preserve_default=False,
        ),
    ]
