# Generated by Django 2.2 on 2019-05-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_projects', '0024_dataprojectoutput_related_documentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprojectoutput',
            name='pub_med_id',
            field=models.CharField(default='hello', max_length=50),
            preserve_default=False,
        ),
    ]
