# Generated by Django 2.2 on 2019-05-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_projects', '0025_dataprojectoutput_pub_med_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataprojectoutput',
            name='pub_med_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
