# Generated by Django 2.2 on 2019-05-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_projects', '0027_auto_20190510_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataprojectoutput',
            name='output_type',
            field=models.CharField(choices=[('Government report', 'Government report'), ('Conference paper', 'Conference paper'), ('Journal article', 'Journal article'), ('App or notebook', 'App or notebook')], max_length=200),
        ),
    ]
