# Generated by Django 2.2 on 2019-05-10 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_projects', '0028_auto_20190510_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_type', models.CharField(max_length=100)),
                ('approval_reference', models.CharField(max_length=100)),
                ('approval_agency', models.CharField(max_length=100)),
                ('approval_contact_name', models.CharField(max_length=255)),
                ('data_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_projects.DataProject')),
                ('data_project_output', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_projects.DataProjectOutput')),
            ],
        ),
    ]
