# Generated by Django 2.2 on 2019-05-10 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_projects', '0029_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='data_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_projects.DataProject'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='data_project_output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_projects.DataProjectOutput'),
        ),
    ]
