# Generated by Django 2.2 on 2019-05-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_projects', '0030_auto_20190510_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='in_place',
            field=models.BooleanField(default=False),
        ),
    ]
