# Generated by Django 2.2 on 2019-05-10 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_projects', '0031_approval_in_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approval',
            old_name='in_place',
            new_name='granted',
        ),
    ]
