# Generated by Django 2.2 on 2019-05-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_projects', '0033_auto_20190510_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approval_agency',
            field=models.CharField(choices=[('Aboriginal Health and Medical Research Council of NSW', 'Aboriginal Health and Medical Research Council of NSW'), ('ACT Health Human Research Ethics Committee', 'ACT Health Human Research Ethics Committee'), ('Australian Institute of Health and Welfare Ethics Committee', 'Australian Institute of Health and Welfare Ethics Committee'), ('Not applicable', 'Not applicable')], max_length=100),
        ),
    ]
