# Generated by Django 2.2 on 2019-05-10 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_projects', '0034_auto_20190510_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataprojectoutput',
            name='has_atsi_content',
        ),
    ]
