# Generated by Django 2.2 on 2019-05-10 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_projects', '0035_remove_dataprojectoutput_has_atsi_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Approval',
            new_name='RequiredApproval',
        ),
    ]
