# Generated by Django 2.2 on 2019-05-23 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_projects', '0037_auto_20190510_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataproject',
            name='ethics_id',
        ),
        migrations.RemoveField(
            model_name='dataproject',
            name='utlizes_grant_funding',
        ),
    ]
