# Generated by Django 2.2 on 2019-05-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_projects', '0038_auto_20190523_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='requiredapproval',
            name='approval_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requiredapproval',
            name='approval_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
