# Generated by Django 2.2 on 2019-05-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_projects', '0039_auto_20190523_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requiredapproval',
            name='approval_agency',
        ),
        migrations.RemoveField(
            model_name='requiredapproval',
            name='approval_type',
        ),
        migrations.AddField(
            model_name='requiredapproval',
            name='approval_body',
            field=models.CharField(default='CI Ethics', max_length=100),
            preserve_default=False,
        ),
    ]
