# Generated by Django 2.2 on 2019-05-23 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_projects', '0040_auto_20190523_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requiredapproval',
            old_name='approval_body',
            new_name='approval_from',
        ),
    ]
