# Generated by Django 2.2 on 2019-05-24 00:22

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('data_projects', '0041_auto_20190524_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataproject',
            name='summary',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='dataprojectoutput',
            name='summary',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
