# Generated by Django 2.2.1 on 2019-05-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_projects', '0042_auto_20190524_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprojectoutput',
            name='working_folder',
            field=models.CharField(default='fix', max_length=200),
            preserve_default=False,
        ),
    ]
