# Generated by Django 2.2.1 on 2019-05-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_assets', '0008_auto_20190525_1517'),
        ('data_projects', '0044_dataproject_working_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprojectoutput',
            name='data_assets',
            field=models.ManyToManyField(to='data_assets.DataAsset'),
        ),
    ]
