# Generated by Django 2.2.1 on 2019-05-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_projects', '0045_dataprojectoutput_data_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataproject',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
