# Generated by Django 2.1.5 on 2019-02-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarequest',
            name='current_status',
            field=models.CharField(choices=[('Awaiting triage', 'Awaiting triage'), ('Being processed', 'Being processed'), ('Approved', 'Approved'), ('Not approved', 'Not approved'), ('On hold', 'On hold')], max_length=255),
        ),
    ]
