# Generated by Django 2.1.7 on 2019-03-12 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190211_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datarequest',
            name='title_or_summary',
        ),
    ]
