# Generated by Django 2.1.7 on 2019-03-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190312_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarequest',
            name='current_status',
            field=models.CharField(choices=[('Awaiting triage', 'Awaiting triage'), ('Being processed', 'Being processed'), ('Approved', 'Approved'), ('Not approved', 'Not approved'), ('On hold', 'On hold'), ('Closed', 'Closed')], max_length=255),
        ),
    ]
