# Generated by Django 2.2 on 2019-05-23 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190315_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datarequest',
            old_name='seeking_atsi_data',
            new_name='seeking_conentious_data',
        ),
        migrations.RemoveField(
            model_name='datarequest',
            name='seeking_clincr_variables',
        ),
        migrations.RemoveField(
            model_name='datarequest',
            name='seeking_codurf_data',
        ),
    ]
