# Generated by Django 2.2 on 2019-05-23 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20190524_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datarequest',
            old_name='seeking_conentious_data',
            new_name='seeking_contentious_data',
        ),
    ]
