# Generated by Django 2.2 on 2019-04-22 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_and_notebooks', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RLibrary',
        ),
    ]
