# Generated by Django 2.1.7 on 2019-03-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataassetrole',
            name='type',
            field=models.CharField(choices=[('Data Sponsor', 'Data Sponsor'), ('Data Custodian', 'Data Custodian'), ('Data Steward', 'Data Steward'), ('Data User', 'Data User'), ('Business Owner', 'Business Owner'), ('System Owner', 'System Owner'), ('System User', 'System User')], max_length=100),
        ),
    ]
