# Generated by Django 2.2 on 2019-04-22 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_assets', '0003_auto_20190418_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataasset',
            name='data_limiting_marker',
        ),
        migrations.AddField(
            model_name='dataasset',
            name='data_sensitivity_level',
            field=models.CharField(choices=[('For Official Use Only', 'For Official Use Only'), ('Sensitive - Personal data', 'Sensitive - Personal data'), ('For public use', 'For public use')], default='For public use', max_length=200),
            preserve_default=False,
        ),
    ]
