# Generated by Django 2.2 on 2019-05-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_assets', '0004_auto_20190423_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataassetbreach',
            name='mitigation',
            field=models.TextField(default='blah'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataassetbreach',
            name='mitigation_completed',
            field=models.BooleanField(default=False),
        ),
    ]
