# Generated by Django 2.2 on 2019-05-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_assets', '0005_auto_20190524_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataasset',
            name='version',
            field=models.CharField(max_length=200),
        ),
    ]
