# Generated by Django 2.2.1 on 2019-05-24 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_assets', '0006_auto_20190524_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataasset',
            name='data_sensitivity_level',
            field=models.CharField(choices=[('For Official Use Only', 'For Official Use Only'), ('Sensitive - Personal', 'Sensitive - Personal'), ('Sensitive - Health Information', 'Sensitive - Health Information'), ('Senstitive - Legal', 'Senstitive - Legal'), ('Senstitive - NSW Government', 'Senstitive - NSW Government'), ('Senstitive - NSW Cabinet', 'Senstitive - NSW Cabinet')], max_length=200),
        ),
    ]
