# Generated by Django 2.2.1 on 2019-05-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_assets', '0007_auto_20190524_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataasset',
            name='data_location_type',
            field=models.CharField(choices=[('Web Resource', 'Web Resource'), ('Internal Server', 'Internal Server'), ('Internal Restricted Share', 'Internal Restricted Share'), ('External Server', 'External Server')], max_length=200),
        ),
    ]
