# Generated by Django 2.2.1 on 2019-05-26 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_assets', '0008_auto_20190525_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataelement',
            name='legacy_collection',
        ),
    ]
