# Generated by Django 2.2.1 on 2019-05-26 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_assets', '0009_remove_dataelement_legacy_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataelement',
            name='accepted_values',
        ),
    ]
