# Generated by Django 2.1.5 on 2019-02-11 05:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('data_projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteOrTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time_created', models.DateTimeField(auto_now_add=True)),
                ('detail', models.TextField()),
                ('date_due', models.DateField(blank=True, default=datetime.datetime.now)),
                ('task_completed', models.BooleanField(default=False)),
                ('restricted_to_admin_staff', models.BooleanField(default=False)),
                ('allocated_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_allocated_to', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_created_by', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_projects.DataProject')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.DataRequest')),
            ],
        ),
    ]
