# Generated by Django 2.1.5 on 2019-02-11 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_and_tasks', '0002_noteortask_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noteortask',
            old_name='project',
            new_name='related_project',
        ),
        migrations.RenameField(
            model_name='noteortask',
            old_name='request',
            new_name='related_request',
        ),
    ]
