# Generated by Django 2.1.5 on 2019-02-11 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes_and_tasks', '0003_auto_20190211_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteortask',
            name='allocated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_allocated_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='noteortask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
