# Generated by Django 2.2.1 on 2019-05-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_and_tasks', '0006_auto_20190510_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteortask',
            name='detail',
            field=models.TextField(null=True),
        ),
    ]
